### ISSUE TITLE
Not working with recent nightly 6.99

### ISSUE THREAD

**Issue by Robyrob** [pcbway/PCBWay-Plug-in-for-Kicad#6]
Using it with recent nightly release, it stop working.
I think because kicad programmer changed the option "SetExcludeEdgeLayer()

**Comment by pcbway** [comment]
Hi,I didn't get the meaning.
We just tried,it is workig well.
Could you tell me the details?

**Comment by Robyrob** [comment]
I am using the nightly version of Kicad:
Version: (6.99.0-2815-gbbc0c61ccb), release build in Windows 64
In stable version of kicad 6.0 Your plugin is working; in nightly version it doesn't work. The procession bar stop and the files are not generated.
In the python console the message is:'PCB_PLOT_PARAMS' object has no attribute 'SetExcludeEdgeLayer'

**Comment by pcbway** [comment]
Thanks,I will contact with KiCAD team about this.

**Comment by sethhillbrand** [comment]
The line 

```python
        popt.SetExcludeEdgeLayer(True)
```

Should be

```python
        if hasattr(popt, "SetExcludeEdgeLayer"):
            popt.SetExcludeEdgeLayer(True)
```

**Comment by pcbway** [comment]
Thansk for the help,last time we didn't find the way out

**Comment by greggjaskiewicz** [comment]
it doesn't work wth the 7.0rc1 still. Please make sure it does, because many of us are using it and trying to push designs using this plugin.

**Comment by jonaslee228** [comment]
Yes I agree. It is very unhandy to have this not working. Please fix it soon.

**Comment by subst4nc3** [comment]
KEEP IN MIND THAT I'M NOT A PROGRAMMER....
so the modification are proposed without any warranty and i'm not responsible if you receive an incorrect board made with these modifications.

Hello, i have managed to make it working again by changing and adding some lines in the thread.py file, according to the changes made to another similiar plugin (AISLER):

modify (as suggest by sethhillbrand) from:
         popt.SetExcludeEdgeLayer(True)
to:

        if hasattr(popt, "SetExcludeEdgeLayer"):
            popt.SetExcludeEdgeLayer(True)


modify from:
         boardWidth = pcbnew.Iu2Millimeter(board.GetBoardEdgesBoundingBox().GetWidth())
         boardHeight = pcbnew.Iu2Millimeter(board.GetBoardEdgesBoundingBox().GetHeight())
to:
         boardWidth = pcbnew.ToMM(board.GetBoardEdgesBoundingBox().GetWidth())
         boardHeight = pcbnew.ToMM(board.GetBoardEdgesBoundingBox().GetHeight())

----add:
            angle = f.GetOrientation()
            try: # kicad >= 6.99
                angle = angle.AsDegrees()
            except AttributeError: # kicad <7
                angle /= 10.0
---before components.append({ statement.



modify from:
                'rotation': f.GetOrientation() / 10.0,
to:
                'rotation': angle,

**Comment by pcbway** [comment]
Now we have solved the problem and updated the plugin that suitable for version7

**Comment by greggjaskiewicz** [comment]
still not available in Kicad itself tho.

**Comment by KanyonKris** [comment]
Version 0.1.3 works for me in KiCad 7. Downloaded the plugin and installed manually. I assume version 0.1.3 will be added to the official KiCad plugin repository eventually.

**Comment by pcbway** [comment]
We will add to the official KiCad plugin repository in gitlab soon
